"""empty message

Revision ID: 104a7e841e24
Revises: None
Create Date: 2015-07-22 23:14:28.568000

"""

# revision identifiers, used by Alembic.
revision = '104a7e841e24'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foodName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food')
    ### end Alembic commands ###
