"""empty message

Revision ID: 5a4a99f0060a
Revises: None
Create Date: 2015-07-31 18:49:06.130000

"""

# revision identifiers, used by Alembic.
revision = '5a4a99f0060a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cookName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foodName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nationName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tasteName', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timeName', sa.String(length=128), nullable=True),
    sa.Column('startTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('targetEnum', sa.Enum('Food', 'Cook', 'Taste', 'Nation'), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_score')
    op.drop_table('time')
    op.drop_table('taste')
    op.drop_table('nation')
    op.drop_table('food')
    op.drop_table('cook')
    ### end Alembic commands ###
